### ISSUE TITLE
Populate the inventory page

### ISSUE THREAD

**Issue by JamesSchwellenbach** [ucsb-cs148-s21/1pm-t2-food-bank#32]
Get the inventory data from the back end as to the quantities of the different food items

acceptance criteria:  
- [ ] dynamic inventory page

**Comment by lwu5** [comment]
Not part of the MVP push to future sprint

**Comment by lwu5** [comment]
page created but hasnt been linked to database and need further visual design as well

**Comment by lwu5** [comment]
dup
