### ISSUE TITLE
staff portal page

### ISSUE THREAD

**Issue by missmiss20** [ucsb-cs148-s21/1pm-t2-food-bank#42]
acceptance criteria:  
- [ ] The staff portal page is openable with all content displaying.
- [ ] Users can see staff information on the page.

I don't think we are planning on implementing this anymore. Jerry do not start working on this without discussing it with the team :)

**Comment by lwu5** [comment]
I don't think we are planning on implementing this anymore. Jerry do not start working on this without discussing it with the team :)
