### ISSUE TITLE
Timestamp for `inventory` page

### ISSUE THREAD

**Issue by JamesSchwellenbach** [ucsb-cs148-s21/1pm-t2-food-bank#61]
as a student I can check the web app and see the latest time inventory was updated by staff, (which is what the timestamp used to indicate) so I can know if the data on the inventory page are up-to-date.

acceptance criteria:  
- [x] On the inventory and staff page there is a timestamp.
- [x] The timestamp shows the most recent time the database was updated through the staff portal.

**Comment by lwu5** [comment]
Orion checked the feasibility of the function: 
[There]{https://stackoverflow.com/questions/53409430/getting-last-update-information-firebase} isn't an explicit function to return the most recently updated time, but there are some code snippets to show how to implement it and it should be fairly easy.

Sunrise will do the code implementation
